
const DATOS_LUGARES = [
  {
    "ID": "CAN-NIA-01",
    "Padre": "CAN-NIA",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 3,
    "Orden": 6,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Cataratas del Niágara",
    "Pais": "Canadá",
    "Ciudad": "Niágara",
    "latitud": 43.08577,
    "longitud": -79.07626,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Natural",
    "Tipo_de_magia": "Poder Celestial",
    "Descripcion_corta": "Al amanecer, el agua se vuelve oro y el ruido del mundo desaparece. Ahí, sin buscarlo, Kaira tocó por un instante algo que era solo silencio, luz blanca y la certeza de estar en el corazón de algo inmenso.",
    "Imagen": "can_nia_01.jpg"
  },
  {
    "ID": "FR-PAR-04",
    "Padre": "FR-PAR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 13,
    "Orden": 22,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Ópera Garnier",
    "Pais": "Francia",
    "Ciudad": "París",
    "latitud": 48.87223,
    "longitud": 2.33169,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Bajo el mármol y las lámparas dignas de un cuento, unas aguas quietas guardan un secreto que ningún turista sospecha: un camino hacia el lugar donde Europa ha resguardado su memoria mágica durante siglos",
    "Imagen": "fr_par_04.jpg"
  },
  {
    "ID": "FR-PAR-01",
    "Padre": "FR-PAR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 12,
    "Orden": 19,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Las calles de París",
    "Pais": "Francia",
    "Ciudad": "París",
    "latitud": 48.8546,
    "longitud": 2.28941,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Especial",
    "Tipo_de_magia": "Sin magia",
    "Descripcion_corta": "La ciudad de la luz recibió a Kaira entre vitrinas navideñas, hechizos que salieron mal antes del desayuno y una Nochebuena compartida con Daniella y Stefen entre vino caliente y castañas, un capítulo de una aventura que apenas empezaba a mostrar su otro lado.",
    "Imagen": "fr_par_01.jpg"
  },
  {
    "ID": "FR-PAR-02",
    "Padre": "FR-PAR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 12,
    "Orden": 20,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Sacré-Cœur / Montmartre",
    "Pais": "Francia",
    "Ciudad": "París",
    "latitud": 48.88694,
    "longitud": 2.34314,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Sin magia",
    "Descripcion_corta": "Entre pintores callejeros y el aroma a pan recién horneado, Kaira bajó estas calles empinadas queriendo perderse en el presente. Pero ni el crepe más delicioso pudo borrar la pregunta que empezaba a dolerle: ¿cuánto de lo compartido con Jeziel era elección, y cuánto solo una misión?",
    "Imagen": "fr_par_02.jpg"
  },
  {
    "ID": "FR-PAR-03",
    "Padre": "FR-PAR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 12,
    "Orden": 21,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Bois de Boulogne",
    "Pais": "Francia",
    "Ciudad": "París",
    "latitud": 48.8621,
    "longitud": 2.25232,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Natural",
    "Tipo_de_magia": "Sin magia",
    "Descripcion_corta": "Bajo faroles y árboles desnudos, un círculo de hebras doradas guardó las primeras lecciones de Kaira: cómo hacer magia, y cómo esconderla después. Ahí aprendió que el hilo plateado que la delataba, distinto al de todos, no se borraba con un simple movimiento de mano.",
    "Imagen": "fr_par_03.jpg"
  },
  {
    "ID": "GB-LON-05",
    "Padre": "GB-LON",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 7,
    "Orden": 15,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Observatorio de Greenwich",
    "Pais": "Reino Unido",
    "Ciudad": "Londres",
    "latitud": 51.47731,
    "longitud": -0.00054,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Sin magia",
    "Descripcion_corta": "Al final de un camino que sube sin sentirse, un rayo verde parte el mundo en dos con precisión milimétrica. Ahí, entre relojes astronómicos y la ciudad encendiéndose a lo lejos, Kaira se preguntó por primera vez cuántos secretos mágicos podía guardar el mundo entero, no solo el suyo.",
    "Imagen": "gb_lon_05.jpg"
  },
  {
    "ID": "GB-LON-01",
    "Padre": "GB-LON",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 5,
    "Orden": 8,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Londres",
    "Pais": "Reino Unido",
    "Ciudad": "Londres",
    "latitud": 51.50936,
    "longitud": -0.15463,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Especial",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Entre Piccadilly, Winter Wonderland y las letras de LOVE, Londres esconde también un callejón empedrado donde varitas de utilería y calderos humeantes imitan una magia que, sin que casi nadie lo sepa, sí existe a la vuelta de la esquina.",
    "Imagen": "gb_lon_1.jpg"
  },
  {
    "ID": "GB-LON-02",
    "Padre": "GB-LON",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 5,
    "Orden": 9,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Abadía de Westminster",
    "Pais": "Reino Unido",
    "Ciudad": "Londres",
    "latitud": 51.49966,
    "longitud": -0.12734,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Residual",
    "Descripcion_corta": "Solamente en compañía de su ángel particular, Kaira se asombró de los vitrales góticos. Entre tumbas de reyes y científicos descubrió un resplandor que solo ella podía ver. No tenía certeza de que era exactamente, y prefirió no preguntar demasiado.",
    "Imagen": "gb_lon_02.jpg"
  },
  {
    "ID": "GB-LON-03",
    "Padre": "GB-LON",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 5,
    "Orden": 10,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Torre de Londres",
    "Pais": "Reino Unido",
    "Ciudad": "Londres",
    "latitud": 51.50836,
    "longitud": -0.07602,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Residual",
    "Descripcion_corta": "Un castillo normando donde Jeziel invocó, con poder celestial, guardias y nobles de otra época, hasta llegar a las mazmorras, donde el encanto se rompió de golpe: una energía oscura y un dolor ajeno que Kaira sintió en la piel mucho después de haber salido.",
    "Imagen": "gb_lon_03.jpg"
  },
  {
    "ID": "GB-LON-04",
    "Padre": "GB-LON",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 7,
    "Orden": 14,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Museo de Londres",
    "Pais": "Reino Unido",
    "Ciudad": "Londres",
    "latitud": 51.52056,
    "longitud": -0.12734,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Museo",
    "Tipo_de_magia": "Magia Residual",
    "Descripcion_corta": "La Piedra Rosetta brilló con una luz plateada que solo Kaira pudo ver, el primer indicio de que algo en ella empezaba a despertar. Entre los mármoles del Partenón y los toros alados de Mesopotamia, esa misma luz antigua reaparecería, recordándole que no todo lo que brilla ahí es solo historia.",
    "Imagen": "gb_lon_04.jpg"
  },
  {
    "ID": "GB-VBR-05",
    "Padre": "GB-VBR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 9,
    "Orden": 17,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Biblioteca Antigua",
    "Pais": "Reino Unido",
    "Ciudad": "Villa Bretona",
    "latitud": 57.07134,
    "longitud": -3.66894,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Biblioteca",
    "Tipo_de_magia": "Magia Ancestral",
    "Descripcion_corta": "Tras una puerta tallada con símbolos que Kaira reconoció sin saber por qué, la sala más resguardada del castillo guarda la profecía original y sus traducciones, un juego de teléfono descompuesto de siglos, del que depende, sin que nadie se lo diga del todo, mucho más de lo que le cuentan.",
    "Imagen": "gb_vbr_05.jpg"
  },
  {
    "ID": "GB-VBR-01",
    "Padre": "GB-VBR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 5,
    "Orden": 11,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Villa Bretona",
    "Pais": "Reino Unido",
    "Ciudad": "Villa Bretona",
    "latitud": 57.07134,
    "longitud": -3.66894,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Al pie del Ben Macdui, un sendero de niebla lleva a un pueblo medieval que se siente vivo de verdad: la fuente de Merlín, animales que parecen alebrijes, capas que desfilan solas, libros que vuelan y guantes que se sienten como una segunda piel.",
    "Imagen": "gb_vbr_01.jpg"
  },
  {
    "ID": "GB-VBR-02",
    "Padre": "GB-VBR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 5,
    "Orden": 12,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Academia Braeiach",
    "Pais": "Reino Unido",
    "Ciudad": "Villa Bretona",
    "latitud": 57.07134,
    "longitud": -3.66894,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Academia",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Sobre una colina, con muros de piedra casi negra que parecen fundirse con el paisaje, el castillo se alza al final de una subida empinada donde el pueblo, el bosque y un río plateado quedan atrás. Dentro, hasta la arquitectura desafía la lógica: escaleras que aparecen y desaparecen bajo los pies, y una puerta suspendida en el aire que solo la magia sabe alcanzar.",
    "Imagen": "gb_vbr_02.jpg"
  },
  {
    "ID": "GB-VBR-03",
    "Padre": "GB-VBR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 5,
    "Orden": 13,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Biblioteca de la Academia Braeiach",
    "Pais": "Reino Unido",
    "Ciudad": "Villa Bretona",
    "latitud": 57.07134,
    "longitud": -3.66894,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Biblioteca",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Cinco pisos de libros alrededor de una sala silenciosa, organizados con fichas y archiveros tan comunes como cualquier biblioteca; hasta que Kaira abre uno: cada página exhala su propio aroma, su propia brisa, su propio mundo, como si estuviera hecha para despertar la imaginación de quien la lee.",
    "Imagen": "gb_vbr_03.jpg"
  },
  {
    "ID": "GB-VBR-04",
    "Padre": "GB-VBR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 8,
    "Orden": 16,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Prado de la magia",
    "Pais": "Reino Unido",
    "Ciudad": "Villa Bretona",
    "latitud": 57.076284,
    "longitud": -3.690826,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Natural",
    "Tipo_de_magia": "Vórtice de Magia",
    "Descripcion_corta": "Bajo una cúpula donde nunca nieva, el aire vibra con hebras de luz doradas y platinadas: vivas, curiosas, hambrientas. Ahí Kaira aprendió a recolectar magia con las manos... y a un paso de perderse en ella, aprendió también a dejarla ir.",
    "Imagen": "gb_vbr_04.jpg"
  },
  {
    "ID": "GB-VBR-06",
    "Padre": "GB-VBR",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 9,
    "Orden": 18,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Abadía de Whitby",
    "Pais": "Reino Unido",
    "Ciudad": "Villa Bretona",
    "latitud": 54.48859,
    "longitud": -0.60784,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Vórtice de Magia",
    "Descripcion_corta": "Al final de una escalinata interminable sobre el acantilado, entre ruinas donde tres tipos de magia se entrelazan como telarañas de luz, una losa negra reconoció a Kaira antes que nadie más pudiera acercarse. Lo que pasó después, ni Jeziel pudo presenciarlo de cerca.",
    "Imagen": "gb_vbr_06.jpg"
  },
  {
    "ID": "GB-VBR",
    "Padre": "GB-VBR",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Villa Bretona",
    "Pais": "Reino Unido",
    "Ciudad": "Villa Bretona",
    "latitud": 57.07134,
    "longitud": -3.66894,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "gb_vbr.jpg"
  },
  {
    "ID": "IT-ROM-09",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 18,
    "Orden": 38,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Barrio Trevi subterráneo",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.9005,
    "longitud": 12.48406,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Ancestral",
    "Descripcion_corta": "Bajo una pared que parece cualquiera, unas escaleras que ondulan llevan siglos hacia abajo: una ciudad de mármol y agua cristalina, más antigua que la antigua Roma, que los vedlys reclamaron para sí en secreto. Al salir, la Fontana di Trevi espera arriba, como si siempre hubiera sabido guardar ese otro tesoro.",
    "Imagen": "it_rom_09.jpg"
  },
  {
    "ID": "IT-ROM-03",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 16,
    "Orden": 32,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Termas de Caracalla",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.87932,
    "longitud": 12.49266,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Poder Celestial",
    "Descripcion_corta": "Cerradas y ya en penumbra, las ruinas, tan vastas como un estadio, cobraron vida bajo el poder celestial de Jeziel: bóvedas transparentes, mosaicos que recuperaban su color, una piscina que volvía a llenarse solo para los ojos de Kaira. Todo, menos el calor del agua, que el tiempo no le devolvió al espejismo.",
    "Imagen": "it_rom_03.jpg"
  },
  {
    "ID": "IT-ROM-05",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 17,
    "Orden": 34,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Roma Imperial",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.8911,
    "longitud": 12.48984,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Poder Celestial",
    "Descripcion_corta": "Con un giro y los ojos cerrados, Jeziel devolvió a la vida la Roma de Trajano: senadores con togas púrpura, gladiadores, carreras de cuadrigas y un Coliseo completo bajo el sol. Todo real para los sentidos; y un templo al que Jeziel, por alguna razón que no explicó, nunca quiso entrar.",
    "Imagen": "it_rom_05.jpg"
  },
  {
    "ID": "IT-ROM-10",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 19,
    "Orden": 39,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Coliseo",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.89084,
    "longitud": 12.4922,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Poder Celestial",
    "Descripcion_corta": "Todos los caminos llevan al Coliseo. Desde el prado, entre fuegos artificiales y doce destellos que anunciaron el año nuevo, Kaira sintió un eco de algo ya vivido, imposible de nombrar. Horas después, con el Coliseo brillando a la distancia, cambió de año acurrucada junto a su ángel.",
    "Imagen": "it_rom_10.jpg"
  },
  {
    "ID": "IT-ROM-06",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 18,
    "Orden": 35,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Basílica de San Pedro",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.90224,
    "longitud": 12.45391,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Poder Celestial",
    "Descripcion_corta": "Antes del amanecer, en una basílica casi vacía, la gratitud de Kaira se convirtió en luz desbordada, sentida por toda Roma. Huyeron entre gelato y susurros de «más lejos», dejando atrás una ciudad con un escudo nuevo que antes no existía.",
    "Imagen": "it_rom_06.jpg"
  },
  {
    "ID": "IT-ROM-01",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 16,
    "Orden": 30,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Paseo por Roma",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.89662,
    "longitud": 12.48529,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Especial",
    "Tipo_de_magia": "Sin magia",
    "Descripcion_corta": "Un día de turismo genuinamente humano: techos de oro, obeliscos egipcios e iglesias sobre iglesias sobre iglesias. Bajo la Porta Maggiore, sin embargo, apareció algo distinto: una basílica subterránea communia, olvidada bajo Roma durante siglos, con dragones y seres alados que nadie más recuerda.",
    "Imagen": "paseo_roma.jpg"
  },
  {
    "ID": "IT-ROM-07",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 18,
    "Orden": 36,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Barrio Vedlys",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.9186,
    "longitud": 12.46939,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Especial",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Un barrio entero, camuflado por un hechizo tan elegante que los communia lo cruzan sin notar nada. Kaira, mareada por ver ambas realidades a la vez, aprende a enfocar cada una a voluntad. Lo que ve ahí termina siendo una anomalía que ni el propio Stefen sabe explicar.",
    "Imagen": "it_rom_07.jpg"
  },
  {
    "ID": "IT-ROM-02",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 16,
    "Orden": 31,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Porta San Paolo y Pirámide Cesia",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.87654,
    "longitud": 12.48083,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Residual",
    "Descripcion_corta": "Siguiendo la muralla, Kaira descubrió que en Roma la magia vive dentro de la piedra misma. Una puerta la cruzó al primer vestigio del Imperio; una pirámide, incrustada en el muro y bañada en blanco antinatural, casi la absorbió por completo, destellos tan densos que no supo distinguir dónde terminaba la historia y dónde comenzaba la magia.",
    "Imagen": "it_rom_02.jpg"
  },
  {
    "ID": "IT-ROM-04",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 16,
    "Orden": 33,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Muralla Aureliana",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.87385,
    "longitud": 12.50144,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Residual",
    "Descripcion_corta": "Sobre una muralla de veinte metros, siglos de historia se leen en capas de piedra; y entretejida en ellas, magia dorada y platinada que nunca deja de renovar su firma. Ahí, sin varita, Kaira recolectó su primera magia perdida a mano limpia, guiada solo por el zumbido de la piedra bajo sus dedos..",
    "Imagen": "it_rom_04.jpg"
  },
  {
    "ID": "IT-ROM-08",
    "Padre": "IT-ROM",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 18,
    "Orden": 37,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Panteón de Roma",
    "Pais": "Italia",
    "Ciudad": "Roma",
    "latitud": 41.89865,
    "longitud": 12.4769,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Vórtice de Magia",
    "Descripcion_corta": "Bajo el óculo que deja caer un solo rayo de luz, la magia de Roma entera parece haberse concentrado en este vórtice. Aquí Kaira, sin querer, hizo desaparecer a todo un salón de turistas. Tambiénaprendió, con cristales creados de su propia mano, cómo tomar solo lo que le correspondía sin llevarse el lugar entero consigo.",
    "Imagen": "it_rom_08.jpg"
  },
  {
    "ID": "MEX-MEX-01",
    "Padre": "MEX-MEX",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 2,
    "Orden": 3,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Ciudad de México",
    "Pais": "México",
    "Ciudad": "Ciudad de México",
    "latitud": 19.43465,
    "longitud": -99.13183,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Sin magia",
    "Descripcion_corta": "El primer paseo de Kaira con su ángel, sin magia de por medio: el Templo Mayor bajo el nivel de la calle, una catedral que se hunde poco a poco sobre templos ajenos, y la frase con la que Kaira resume lo que es viajar: «tocar el alma de un lugar».",
    "Imagen": "mex_mex_01.jpg"
  },
  {
    "ID": "MEX-PAG-01",
    "Padre": "MEX-PAG",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 4,
    "Orden": 7,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Pueblo del Águila",
    "Pais": "México",
    "Ciudad": "Pueblo del Águila",
    "latitud": 26.69931,
    "longitud": -103.74366,
    "Naturaleza": "ficticio",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "En elTras horas de calor, torbellinos y brújulas enloquecidas por el desierto, el Atlas llevó a Kaira hasta un pueblo fantasma: casas en ruinas, una fuente sin agua en décadas, calles vacías. Pero lo que ella veía y lo que Jeziel preguntaba insistentemente si veía no eran, quizás, la misma cosa.",
    "Imagen": "pueblo_destruido.jpg"
  },
  {
    "ID": "MEX-PUE-01",
    "Padre": "MEX-PUE",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 2,
    "Orden": 4,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Pirámide de Cholula",
    "Pais": "México",
    "Ciudad": "Puebla",
    "latitud": 19.05714,
    "longitud": -98.30322,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Poder Celestial",
    "Descripcion_corta": "Cerrado al público desde hace años, un solo deseo bastó para que Jeziel disolviera a Kaira dentro de él: un túnel donde los murales se ven recién pintados bajo luz seráfica, y del que salieron atravesando una reja cerrada como si no existiera.",
    "Imagen": "mex_pue_01.jpg"
  },
  {
    "ID": "MEX-PUE-02",
    "Padre": "MEX-PUE",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 2,
    "Orden": 5,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Biblioteca Palafoxiana",
    "Pais": "México",
    "Ciudad": "Puebla",
    "latitud": 19.04301,
    "longitud": -98.19857,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Biblioteca",
    "Tipo_de_magia": "Sin magia",
    "Descripcion_corta": "Bajo vitrales que dibujan luz sobre libros centenarios, Patrimonio de la UNESCO, Kaira encontró su tipo de destino favorito: un manuscrito original de Sor Juana, abierto e inmóvil en el tiempo, sus palabras aún vivas después de siglos.",
    "Imagen": "mex_pue_02.jpg"
  },
  {
    "ID": "MEX-TOL-02",
    "Padre": "MEX-TOL",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 1,
    "Orden": 2,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Campo de las hadas",
    "Pais": "México",
    "Ciudad": "Toluca",
    "latitud": 19.294786,
    "longitud": -99.681428,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Natural",
    "Tipo_de_magia": "Magia Ancestral",
    "Descripcion_corta": "Un claro sencillo tras el jardín de Kaira, escondido a quien no sabe buscarlo: una roca central, dos pinos de guardia y un hormigueo eléctrico que ella atribuía a la imaginación. Ahí aprendió a hablar con su hada madrina, mucho antes de saber que la magia también sabe guardar secretos.",
    "Imagen": "mex_tol_02.jpg"
  },
  {
    "ID": "MEX-TOL-01",
    "Padre": "MEX-TOL",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 1,
    "Orden": 1,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Casa de Kaira",
    "Pais": "México",
    "Ciudad": "Toluca",
    "latitud": 19.29528,
    "longitud": -99.682121,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Especial",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Toluca, ciudad donde inicia la historia.",
        "Imagen": "mex_tol_01.jpg"
  },
  {
    "ID": "PANAH-01",
    "Padre": "PANAH",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 14,
    "Orden": 23,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Panah",
    "Pais": "Dimension Alterna",
    "Ciudad": "Panah",
    "latitud": null,
    "longitud": null,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Especial",
    "Tipo_de_magia": "",
    "Descripcion_corta": "Una cabaña de troncos hecha enteramente de los recuerdos de Kaira: la colcha de la abuela, rosas de Castilla, gardenias, una vista de montaña que nunca pidió pero siempre quiso. Ahí, siendo ella misma la llave, aprendió por fin a confiar en su propia magia.",
    "Imagen": "panah_02.jpg"
  },
  {
    "ID": "SUI-GIN-02",
    "Padre": "SUI-GIN",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 15,
    "Orden": 25,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Maison Tavel",
    "Pais": "Suiza",
    "Ciudad": "Ginebra",
    "latitud": 46.20156,
    "longitud": 6.1471,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Perdida",
    "Descripcion_corta": "En su jardin interior hay un arbol centenario repleto de magia.",
    "Imagen": "sui_gin_02.jpg"
  },
  {
    "ID": "SUI-GIN-06",
    "Padre": "SUI-GIN",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 15,
    "Orden": 29,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Castillo de Chillon",
    "Pais": "Suiza",
    "Ciudad": "Ginebra",
    "latitud": 46.41433,
    "longitud": 6.92748,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Ancestral",
    "Descripcion_corta": "Uno de sus sótanos lleva a la entrada del Palacio de Cristal.",
    "Imagen": "sui_gin_06.jpg"
  },
  {
    "ID": "SUI-GIN-01",
    "Padre": "SUI-GIN",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 15,
    "Orden": 24,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Ciudad Mágica",
    "Pais": "Suiza",
    "Ciudad": "Ginebra",
    "latitud": 46.22053,
    "longitud": 6.1425,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "Magia Contemporánea",
    "Descripcion_corta": "Es como un centro comercial, y ahí se encuentra Volkov.",
    "Imagen": "sui_gin_01.jpg"
  },
  {
    "ID": "SUI-GIN-05",
    "Padre": "SUI-GIN",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 15,
    "Orden": 28,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Patek Philippe Museum",
    "Pais": "Suiza",
    "Ciudad": "Ginebra",
    "latitud": 46.19889,
    "longitud": 6.13822,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Museo",
    "Tipo_de_magia": "Magia Oscura",
    "Descripcion_corta": "Museo del reloj que oculta secretos, no solo guarda relojes.",
    "Imagen": "sui_gin_05.jpg"
  },
  {
    "ID": "SUI-GIN-03",
    "Padre": "SUI-GIN",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 15,
    "Orden": 26,
    "Nivel_de_visualizacion": "Detalle",
    "Lugar": "Catedral de San Pedro",
    "Pais": "Suiza",
    "Ciudad": "Ginebra",
    "latitud": 46.20155,
    "longitud": 6.14848,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Histórico",
    "Tipo_de_magia": "Magia Residual",
    "Descripcion_corta": "Debajo de ella se encuentra un yacimiento arquelógico de varios niveles.",
    "Imagen": "sui_gin_03.jpg"
  },
  {
    "ID": "SUI-GIN-04",
    "Padre": "SUI-GIN",
    "tipo_de_registro": "Lugar",
    "Libro": 1,
    "Capitulo": 15,
    "Orden": 27,
    "Nivel_de_visualizacion": "Escenario",
    "Lugar": "Biblioteca de Ginebra",
    "Pais": "Suiza",
    "Ciudad": "Ginebra",
    "latitud": 46.19974,
    "longitud": 6.14505,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Biblioteca",
    "Tipo_de_magia": "Magia Entretejida",
    "Descripcion_corta": "Solo se puede entrar con un pase especial. Ahí se encuentran los grimorios mas impotantes de Europa.",
    "Imagen": "sui_gin_04.jpg"
  },
  {
    "ID": "CAN-NIA",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Niagara",
    "Pais": "Canada",
    "Ciudad": "",
    "latitud": 43.894,
    "longitud": -79.10382,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "can_nia.jpg"
  },
  {
    "ID": "PANAH",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Panah",
    "Pais": "Dimension",
    "Ciudad": "",
    "latitud": "",
    "longitud": "",
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Especial",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "panah.jpg"
  },
  {
    "ID": "FR-PAR",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "París",
    "Pais": "Francia",
    "Ciudad": "",
    "latitud": 48.86401,
    "longitud": 2.32734,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "fr_par.jpg"
  },
  {
    "ID": "IT-ROM",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Roma",
    "Pais": "Italia",
    "Ciudad": "",
    "latitud": "",
    "longitud": "",
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "it_rom.jpg"
  },
  {
    "ID": "MEX-MEX",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "CDMX",
    "Pais": "México",
    "Ciudad": "",
    "latitud": 19.43281,
    "longitud": -99.13339,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "mex_mex.jpg"
  },
  {
    "ID": "MEX-PAG",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Pueblo del Aguila",
    "Pais": "México",
    "Ciudad": "",
    "latitud": 26.69931,
    "longitud": -103.74366,
    "Naturaleza": "Ficticio",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "mex_pag.jpg"
  },
  {
    "ID": "MEX-PUE",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Puebla",
    "Pais": "México",
    "Ciudad": "",
    "latitud": 19.0621,
    "longitud": -98.17708,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "mex_pue.jpg"
  },
  {
    "ID": "MEX-TOL",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Toluca",
    "Pais": "México",
    "Ciudad": "",
    "latitud": 19.29415,
    "longitud": -99.65379,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "mex_tol.jpg"
  },
  {
    "ID": "GB-LON",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Londres",
    "Pais": "ReinoUnido",
    "Ciudad": "",
    "latitud": 51.5074,
    "longitud": -0.12763,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "gb_lon.jpg"
  },
  {
    "ID": "SUI-GIN",
    "Padre": "",
    "tipo_de_registro": "Padre",
    "Libro": "",
    "Capitulo": "",
    "Orden": "",
    "Nivel_de_visualizacion": "Ciudad",
    "Lugar": "Ginebra",
    "Pais": "Suiza",
    "Ciudad": "",
    "latitud": 46.20101,
    "longitud": 6.14578,
    "Naturaleza": "Real",
    "tipo_de_lugar": "Ciudad",
    "Tipo_de_magia": "",
    "Descripcion_corta": "",
    "Imagen": "sui_gin.jpg"
  }
];